#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using SmartCRM.DAL;

namespace SmartCRM.DAL	
{
	[Table("companies_employees")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	public partial class CompaniesEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private uint _companyId;
		[Column("CompanyId", OpenAccessType = OpenAccessType.Int32, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_companyId")]
		public virtual uint CompanyId
		{
			get
			{
				return this._companyId;
			}
			set
			{
				if(this._companyId != value)
				{
					this.OnPropertyChanging("CompanyId");
					this._companyId = value;
					this.OnPropertyChanged("CompanyId");
				}
			}
		}
		
		private uint _employeeId;
		[Column("EmployeeId", OpenAccessType = OpenAccessType.Int32, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_employeeId")]
		public virtual uint EmployeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				if(this._employeeId != value)
				{
					this.OnPropertyChanging("EmployeeId");
					this._employeeId = value;
					this.OnPropertyChanged("EmployeeId");
				}
			}
		}
		
		private Employee _employee;
		[ForeignKeyAssociation(ConstraintName = "FK_companies_persons_employees_EmployeeId", SharedFields = "EmployeeId", TargetFields = "Id")]
		[Storage("_employee")]
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				if(this._employee != value)
				{
					this.OnPropertyChanging("Employee");
					this._employee = value;
					this.OnPropertyChanged("Employee");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
