#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace SmartCRM.DAL	
{
	[Table("company_files")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class CompanyFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private bool _isDeleted;
		[Column("IsDeleted", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isDeleted")]
		public virtual bool IsDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if(this._isDeleted != value)
				{
					this.OnPropertyChanging("IsDeleted");
					this._isDeleted = value;
					this.OnPropertyChanged("IsDeleted");
				}
			}
		}
		
		private string _fileName;
		[Column("FileName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fileName")]
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				if(this._fileName != value)
				{
					this.OnPropertyChanging("FileName");
					this._fileName = value;
					this.OnPropertyChanged("FileName");
				}
			}
		}
		
		private uint _fileID;
		[Column("FileID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_fileID")]
		public virtual uint FileID
		{
			get
			{
				return this._fileID;
			}
			set
			{
				if(this._fileID != value)
				{
					this.OnPropertyChanging("FileID");
					this._fileID = value;
					this.OnPropertyChanged("FileID");
				}
			}
		}
		
		private string _fileExtension;
		[Column("FileExtension", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fileExtension")]
		public virtual string FileExtension
		{
			get
			{
				return this._fileExtension;
			}
			set
			{
				if(this._fileExtension != value)
				{
					this.OnPropertyChanging("FileExtension");
					this._fileExtension = value;
					this.OnPropertyChanged("FileExtension");
				}
			}
		}
		
		private DateTime _fileCreateDate;
		[Column("FileCreateDate", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_fileCreateDate")]
		public virtual DateTime FileCreateDate
		{
			get
			{
				return this._fileCreateDate;
			}
			set
			{
				if(this._fileCreateDate != value)
				{
					this.OnPropertyChanging("FileCreateDate");
					this._fileCreateDate = value;
					this.OnPropertyChanged("FileCreateDate");
				}
			}
		}
		
		private byte[] _fileContent;
		[Column("FileContent", OpenAccessType = OpenAccessType.LongVarBinary, Length = 0, Scale = 0, SqlType = "longblob")]
		[Storage("_fileContent")]
		public virtual byte[] FileContent
		{
			get
			{
				return this._fileContent;
			}
			set
			{
				if(this._fileContent != value)
				{
					this.OnPropertyChanging("FileContent");
					this._fileContent = value;
					this.OnPropertyChanged("FileContent");
				}
			}
		}
		
		private uint _companyID;
		[Column("CompanyID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_companyID")]
		public virtual uint CompanyID
		{
			get
			{
				return this._companyID;
			}
			set
			{
				if(this._companyID != value)
				{
					this.OnPropertyChanging("CompanyID");
					this._companyID = value;
					this.OnPropertyChanged("CompanyID");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
