#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace SmartCRM.DAL	
{
	[Table("const_payment_types")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class ConstPaymentType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private uint _paymentTypePosition;
		[Column("PaymentTypePosition", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_paymentTypePosition")]
		public virtual uint PaymentTypePosition
		{
			get
			{
				return this._paymentTypePosition;
			}
			set
			{
				if(this._paymentTypePosition != value)
				{
					this.OnPropertyChanging("PaymentTypePosition");
					this._paymentTypePosition = value;
					this.OnPropertyChanged("PaymentTypePosition");
				}
			}
		}
		
		private string _paymentTypeName;
		[Column("PaymentTypeName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_paymentTypeName")]
		public virtual string PaymentTypeName
		{
			get
			{
				return this._paymentTypeName;
			}
			set
			{
				if(this._paymentTypeName != value)
				{
					this.OnPropertyChanging("PaymentTypeName");
					this._paymentTypeName = value;
					this.OnPropertyChanged("PaymentTypeName");
				}
			}
		}
		
		private uint _paymentTypeID;
		[Column("PaymentTypeID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_paymentTypeID")]
		public virtual uint PaymentTypeID
		{
			get
			{
				return this._paymentTypeID;
			}
			set
			{
				if(this._paymentTypeID != value)
				{
					this.OnPropertyChanging("PaymentTypeID");
					this._paymentTypeID = value;
					this.OnPropertyChanged("PaymentTypeID");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
