#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using SmartCRM.DAL;

namespace SmartCRM.DAL	
{
	[Table("conts_products_types")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class ContsProductsType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _productTypeName;
		[Column("ProductTypeName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_productTypeName")]
		public virtual string ProductTypeName
		{
			get
			{
				return this._productTypeName;
			}
			set
			{
				if(this._productTypeName != value)
				{
					this.OnPropertyChanging("ProductTypeName");
					this._productTypeName = value;
					this.OnPropertyChanged("ProductTypeName");
				}
			}
		}
		
		private uint _productTypeID;
		[Column("ProductTypeID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_productTypeID")]
		public virtual uint ProductTypeID
		{
			get
			{
				return this._productTypeID;
			}
			set
			{
				if(this._productTypeID != value)
				{
					this.OnPropertyChanging("ProductTypeID");
					this._productTypeID = value;
					this.OnPropertyChanged("ProductTypeID");
				}
			}
		}
		
		private IList<Product> _products = new List<Product>();
		[Collection(InverseProperty = "ContsProductsType")]
		[Storage("_products")]
		public virtual IList<Product> Products
		{
			get
			{
				return this._products;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
