#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using SmartCRM.DAL;

namespace SmartCRM.DAL	
{
	[Table("employees")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _firstName;
		[Column("FirstName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_firstName")]
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if(this._firstName != value)
				{
					this.OnPropertyChanging("FirstName");
					this._firstName = value;
					this.OnPropertyChanged("FirstName");
				}
			}
		}
		
		private string _secondName;
		[Column("SecondName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_secondName")]
		public virtual string SecondName
		{
			get
			{
				return this._secondName;
			}
			set
			{
				if(this._secondName != value)
				{
					this.OnPropertyChanging("SecondName");
					this._secondName = value;
					this.OnPropertyChanged("SecondName");
				}
			}
		}
		
		private string _lastName;
		[Column("LastName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_lastName")]
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if(this._lastName != value)
				{
					this.OnPropertyChanging("LastName");
					this._lastName = value;
					this.OnPropertyChanged("LastName");
				}
			}
		}
		
		private string _phone;
		[Column("Phone", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 250, Scale = 0, SqlType = "nvarchar")]
		[Storage("_phone")]
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if(this._phone != value)
				{
					this.OnPropertyChanging("Phone");
					this._phone = value;
					this.OnPropertyChanged("Phone");
				}
			}
		}
		
		private uint _id;
		[Column("Id", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_id")]
		public virtual uint Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _email;
		[Column("Email", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 150, Scale = 0, SqlType = "nvarchar")]
		[Storage("_email")]
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				if(this._email != value)
				{
					this.OnPropertyChanging("Email");
					this._email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}
		
		private string _address;
		[Column("Address", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_address")]
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				if(this._address != value)
				{
					this.OnPropertyChanging("Address");
					this._address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}
		
		private byte[] _photo;
		[Column("Photo", OpenAccessType = OpenAccessType.LongVarBinary, IsNullable = true, Length = 0, Scale = 0, SqlType = "blob")]
		[Storage("_photo")]
		public virtual byte[] Photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if(this._photo != value)
				{
					this.OnPropertyChanging("Photo");
					this._photo = value;
					this.OnPropertyChanged("Photo");
				}
			}
		}
		
		private bool _isDeleted;
		[Column("IsDeleted", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isDeleted")]
		public virtual bool IsDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if(this._isDeleted != value)
				{
					this.OnPropertyChanging("IsDeleted");
					this._isDeleted = value;
					this.OnPropertyChanged("IsDeleted");
				}
			}
		}
		
		private short? _gender;
		[Column("Gender", OpenAccessType = OpenAccessType.Byte, IsNullable = true, Length = 0, Scale = 0, SqlType = "tinyint")]
		[Storage("_gender")]
		public virtual short? Gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if(this._gender != value)
				{
					this.OnPropertyChanging("Gender");
					this._gender = value;
					this.OnPropertyChanged("Gender");
				}
			}
		}
		
		private string _comments;
		[Column("Comments", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_comments")]
		public virtual string Comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if(this._comments != value)
				{
					this.OnPropertyChanging("Comments");
					this._comments = value;
					this.OnPropertyChanged("Comments");
				}
			}
		}
		
		private DateTime _birthday;
		[Column("Birthday", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_birthday")]
		public virtual DateTime Birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if(this._birthday != value)
				{
					this.OnPropertyChanging("Birthday");
					this._birthday = value;
					this.OnPropertyChanged("Birthday");
				}
			}
		}
		
		private IList<CompaniesEmployee> _companiesEmployees = new List<CompaniesEmployee>();
		[Collection(InverseProperty = "Employee")]
		[Storage("_companiesEmployees")]
		public virtual IList<CompaniesEmployee> CompaniesEmployees
		{
			get
			{
				return this._companiesEmployees;
			}
		}
		
		private IList<User> _users = new List<User>();
		[Collection(InverseProperty = "Employee")]
		[Storage("_users")]
		public virtual IList<User> Users
		{
			get
			{
				return this._users;
			}
		}
		
		private IList<Project> _projects = new List<Project>();
		[Collection(InverseProperty = "Employees")]
		[Storage("_projects")]
		public virtual IList<Project> Projects
		{
			get
			{
				return this._projects;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
