#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using SmartCRM.DAL;

namespace SmartCRM.DAL	
{
	[Table("persons")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _personSecondName;
		[Column("PersonSecondName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 80, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personSecondName")]
		public virtual string PersonSecondName
		{
			get
			{
				return this._personSecondName;
			}
			set
			{
				if(this._personSecondName != value)
				{
					this.OnPropertyChanging("PersonSecondName");
					this._personSecondName = value;
					this.OnPropertyChanged("PersonSecondName");
				}
			}
		}
		
		private string _personPhone;
		[Column("PersonPhone", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personPhone")]
		public virtual string PersonPhone
		{
			get
			{
				return this._personPhone;
			}
			set
			{
				if(this._personPhone != value)
				{
					this.OnPropertyChanging("PersonPhone");
					this._personPhone = value;
					this.OnPropertyChanged("PersonPhone");
				}
			}
		}
		
		private string _personName;
		[Column("PersonName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 80, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personName")]
		public virtual string PersonName
		{
			get
			{
				return this._personName;
			}
			set
			{
				if(this._personName != value)
				{
					this.OnPropertyChanging("PersonName");
					this._personName = value;
					this.OnPropertyChanged("PersonName");
				}
			}
		}
		
		private string _personLastName;
		[Column("PersonLastName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 99, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personLastName")]
		public virtual string PersonLastName
		{
			get
			{
				return this._personLastName;
			}
			set
			{
				if(this._personLastName != value)
				{
					this.OnPropertyChanging("PersonLastName");
					this._personLastName = value;
					this.OnPropertyChanged("PersonLastName");
				}
			}
		}
		
		private uint _personID;
		[Column("PersonID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_personID")]
		public virtual uint PersonID
		{
			get
			{
				return this._personID;
			}
			set
			{
				if(this._personID != value)
				{
					this.OnPropertyChanging("PersonID");
					this._personID = value;
					this.OnPropertyChanged("PersonID");
				}
			}
		}
		
		private string _personEmail;
		[Column("PersonEmail", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personEmail")]
		public virtual string PersonEmail
		{
			get
			{
				return this._personEmail;
			}
			set
			{
				if(this._personEmail != value)
				{
					this.OnPropertyChanging("PersonEmail");
					this._personEmail = value;
					this.OnPropertyChanged("PersonEmail");
				}
			}
		}
		
		private string _personAddress;
		[Column("PersonAddress", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_personAddress")]
		public virtual string PersonAddress
		{
			get
			{
				return this._personAddress;
			}
			set
			{
				if(this._personAddress != value)
				{
					this.OnPropertyChanging("PersonAddress");
					this._personAddress = value;
					this.OnPropertyChanged("PersonAddress");
				}
			}
		}
		
		private IList<User> _users = new List<User>();
		[Collection(InverseProperty = "Person")]
		[Storage("_users")]
		public virtual IList<User> Users
		{
			get
			{
				return this._users;
			}
		}
		
		private IList<Company> _companies = new List<Company>();
		[Collection(InverseProperty = "People")]
		[Storage("_companies")]
		public virtual IList<Company> Companies
		{
			get
			{
				return this._companies;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
