#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace SmartCRM.DAL	
{
	[Table("reports")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _reportName;
		[Column("ReportName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 200, Scale = 0, SqlType = "nvarchar")]
		[Storage("_reportName")]
		public virtual string ReportName
		{
			get
			{
				return this._reportName;
			}
			set
			{
				if(this._reportName != value)
				{
					this.OnPropertyChanging("ReportName");
					this._reportName = value;
					this.OnPropertyChanged("ReportName");
				}
			}
		}
		
		private uint _reportID;
		[Column("ReportID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_reportID")]
		public virtual uint ReportID
		{
			get
			{
				return this._reportID;
			}
			set
			{
				if(this._reportID != value)
				{
					this.OnPropertyChanging("ReportID");
					this._reportID = value;
					this.OnPropertyChanged("ReportID");
				}
			}
		}
		
		private string _reportExtension;
		[Column("ReportExtension", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 10, Scale = 0, SqlType = "nvarchar")]
		[Storage("_reportExtension")]
		public virtual string ReportExtension
		{
			get
			{
				return this._reportExtension;
			}
			set
			{
				if(this._reportExtension != value)
				{
					this.OnPropertyChanging("ReportExtension");
					this._reportExtension = value;
					this.OnPropertyChanged("ReportExtension");
				}
			}
		}
		
		private byte[] _reportContain;
		[Column("ReportContain", OpenAccessType = OpenAccessType.LongVarBinary, Length = 0, Scale = 0, SqlType = "longblob")]
		[Storage("_reportContain")]
		public virtual byte[] ReportContain
		{
			get
			{
				return this._reportContain;
			}
			set
			{
				if(this._reportContain != value)
				{
					this.OnPropertyChanging("ReportContain");
					this._reportContain = value;
					this.OnPropertyChanged("ReportContain");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
